name: Publish docs

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    name: Docs publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: |
          pip install -U pip
          poetry install

      - name: Build and deploy
        run: |
          git config --global user.name "thevenuz"
          git config --global user.email "67011477+thevenuz@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
          poetry run mike deploy -p -u $GITHUB_REF_NAME latest
